global:
  nameOverride: ""
  fullnameOverride: ""
  commonCustomLabels:  {}


controller:
  attacher:
    image:
      # quay.io/k8scsi/csi-attacher:v2.2.0  # Orignal. Fails on Kubernetes version 1.25.X
      repository: registry.k8s.io/sig-storage/csi-attacher
      pullPolicy: IfNotPresent
      tag: "v4.2.0"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - amd64
    tolerations: {}
  provisioner:
    image:
      # image: quay.io/k8scsi/csi-provisioner:v2.1.0  # Original.
      repository: registry.k8s.io/sig-storage/csi-provisioner
      pullPolicy: IfNotPresent
      tag: "v2.1.0"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - amd64
    tolerations: {}
  csi_s3:
    image:
      # ctrox/csi-s3:v1.2.0-rc.2   # Original. Is not working for arm64 arch.
      repository: quay.io/vfabi/kube-csi-s3
      pullPolicy: IfNotPresent
      tag: "master"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - amd64
    tolerations: {}


secret:
  accessKeyID: ""
  secretAccessKey: ""
  endpoint: ""  # For AWS set it to "https://s3.<region>.amazonaws.com"
  region: ""  # If not on S3, set it to ""


storageclass:
  reclaimPolicy: "Retain"
  bucket: ""  # To use an existing bucket, specify it here.
  usePrefix: ""  # 'usePrefix' must be "true" in order to enable the prefix feature and to avoid the removal of the prefix or bucket.
  prefix: ""  # 'prefix' can be empty (it will mount on the root of the bucket), an existing prefix or a new one.


examples:
  setup: false
