apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-csi-s3.labels" . | nindent 4 }}
stringData:
  accessKeyID: "{{ .Values.secret.accessKeyID }}"
  secretAccessKey: "{{ .Values.secret.secretAccessKey }}"
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: "{{ .Values.secret.endpoint }}"
  # If not on S3, set it to ""
  region: "{{ .Values.secret.region }}"
